### PR TITLE
Add node colors to paga

### PR DESCRIPTION
**Pull request by michalk8**
Hey @VolkerBergen ,
this PR allows user to specify node colors. If `None`, it's just as before. Marius and I want to use it for pie charts, see this issue https://github.com/theislab/cellrank/issues/134.

### CODE REVIEW

**Comment by michalk8** [comment]
I've removed the `text_kwds` because the nodes I can't get the z-order work with alpha parameter:
setting z-order to 1000 properly renders the text (with 0 being under the node). Adding alpha negates this effect.

**Comment by VolkerBergen** [comment]
> `text_kwds`
Why do you need to remove that? The rationale is that the legend shall be fully controlled via scatter, thus allowing any legend configuration. When removing `text_kwds`, the legend is added twice, via `scatter` and scanpy's `paga`.

**Comment by michalk8** [comment]
Problem is as I stated above: using `text_kwds` causes the cluster names to be under the node (in my case it was a pie chart). Setting z-order for the text doesn't do anything when alpha parameter is present. Setting z-order to high enough number (1000) without the alpha parameter is ok. Ok was also not setting the `text_kwds` altogether, until you've mentioned the legend. So `text_kwds` with zorder but without alpha is the way to go.

**Comment by VolkerBergen** [comment]
Still causes double overlaid legend
image
Needs to be fixed in another way (if not via alpha).

**Comment by michalk8** [comment]
I've added this change: len `paga` handle `'on data'`, otherwise `scatter` will take care of the legend.
This has the problem when `legend_loc=None`, which become `legend_loc='best'`, which results in the following:
scatter
Using `legend_loc='on data'` fixes it, which I think is fine (didn't want to let `paga` handle `'best'` as well.

**Comment by VolkerBergen** [comment]
Yet, now your legend is overdrawn. Is that the desired output really, or would it be better to have a right margin legend in that case? What plot do you get, if you don't do the `text_kwds={'zorder': 1000, 'alpha': legend_loc == 'on data'}` hack?

**Comment by michalk8** [comment]
Without the hack:
double_legend
With it and `legend_loc='on data'`:
```python
x = {i: {'#000000': 0.2} for i in range(8)}
scv.pl.paga(adata, basis='umap', transitions=None,
            color='clusters', node_colors=x, legend_loc='on data')
```
on_data

The only issue is with `legend_loc=None`, where the overdrawing happens, but one can get around that if the legend is placed on data with `legend_loc='on data'`. If the legend is not automatically placed on the data, then it might overlap with the nodes if placed somewhat unfortunately.
I'm not sure what a better solution to this would be, honestly.

**Comment by michalk8** [comment]
@Marius1311 mentioned that I should be more explicit, so here it goes:
`sc.pl.paga` by default supports a pie chart as node, where the user can supply for each PAGA node the chart as follows
```python
x = {i: {'#000000': 0.2} for i in range(8)}
```
The nodes are labeled by indices, then there's the color and the fraction of the pie chart. One supplies it to PAGA as `sc.pl.paga(..., colors=x)`.
scVelo's paga doesn't have this option yet, so I've created argument `node_colors=None`, where user can specify also pie charts as `scv.pl.paga(..., node_colors=x)`.
Currently, the only issue is when `legend_loc=None`, which causes the pie charts to be draw over the nodes, if label is draw on the data. This is fixed when explicitly mentioning `legend_loc='on data'`. At the moment, I don't see a clean solution to this problem.

**Comment by VolkerBergen** [comment]
Thanks for clarifying. I'll have a look in the evening.

**Comment by michalk8** [comment]
@VolkerBergen did you manage to find a better solution?

**Comment by Marius1311** [comment]
It would be really important to merge this soon because such a figure would be very nice for our index page. Thanks everyone!

**Pull request merged**
