### PR TITLE
Fix tl.recover_dynamics

### LINKED ISSUE #1058: scv.tl.recover_dynamics fails
When trying to run `scv.tl.recover_dynamics(adata, n_jobs=8)`, I get 

```pytb
    761 if dm is not None and dm.recoverable:
    762     dm.m = m[idx]
    763     dm.alpha, dm.beta, dm.gamma, dm.pars[:3] = (
--> 764         np.array([dm.alpha, dm.beta, dm.gamma, dm.pars[:3]]) / dm.m[-1]
    765     )
    766     dm.t, dm.tau, dm.t_, dm.pars[4] = (
    767         np.array([dm.t, dm.tau, dm.t_, dm.pars[4]]) * dm.m[-1]
    768     )
    770 return adata if copy else dm

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```
This appears to be a similar error to https://github.com/theislab/scvelo/issues/1044

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.3.0  scanpy==1.9.3  anndata==0.8.0  loompy==3.0.7  numpy==1.24.2  scipy==1.10.1  matplotlib==3.7.0  sklearn==1.1.3  pandas==1.5.3  
```

</details>

### PR DESCRIPTION
**Pull request by Marius1311**
## Changes

* Modifies the way parameters are set in `scv.tl.recover_dynamics`

## Related issues

Closes #1058

### CODE REVIEW

**Review by WeilerP — APPROVED** [review]
Thanks, @Marius1311!

**Comment by Marius1311** [comment]
Hi @MarieCoutelier, did you install scVelo from main?

**Comment by MarieCoutelier** [comment]
Hi Marius,

I installed cellrank with conda (conda install -c conda-forge -c bioconda cellrank) and it took care of the scvelo dependency. The version that it installed is : 
scvelo                    0.2.5              pyhdfd78af_0    biocond

When I try to update it with pip install -U scvelo it does not change, though the browser tab seems to say that the most updated version is 0.2.6.dev0+something. 
Should I install the dev version then? By dlding directly from github? 

Thanks, 
Marie

**Comment by Marius1311** [comment]
Yes, the PR was merged to master on scVelo and there hasn't been a release since, so you fill have to install scVelo from the master branch on github.

**Comment by MarieCoutelier** [comment]
Stupid question, but how can I do that? 
I tried 
```
git clone https://github.com/theislab/scvelo.git
cd scvelo
make
```
but got the error message that there is no target for make. 

I could not find the answer in the README either... 

Thanks!!

**Comment by MarieCoutelier** [comment]
Hi, 

So I tried installing scvelo from git with pip using `pip install git+https://github.com/theislab/scvelo`, and now have v0.3.0                    pypi_0    pypi

I opened python, and tried importing scvelo. Here the error that I get : 
```
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> 
>>> import scvelo as scv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/__init__.py", line 6, in <module>
    from scvelo import plotting as pl
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/plotting/__init__.py", line 3, in <module>
    from .gridspec import gridspec
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/plotting/gridspec.py", line 6, in <module>
    from .scatter import scatter
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/plotting/scatter.py", line 16, in <module>
    from .utils import (
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/plotting/utils.py", line 24, in <module>
    from scvelo.tools.utils import strings_to_categoricals
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/tools/__init__.py", line 14, in <module>
    from ._vi_model import VELOVI
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/tools/_vi_model.py", line 14, in <module>
    from scvi.data import AnnDataManager
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvi/__init__.py", line 11, in <module>
    from . import autotune, data, model, external, utils, criticism
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvi/autotune/__init__.py", line 1, in <module>
    from ._manager import TuneAnalysis, TunerManager
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvi/autotune/_manager.py", line 11, in <module>
    from chex import dataclass
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/chex/_src/pytypes.py", line 19, in <module>
    import jax
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/jax/_src/config.py", line 24, in <module>
    from jax._src import lib
  File "/Users/marie.coutelier/miniconda3/envs/cellrank/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 84, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

What can I do to fix this? 
Thanks!

**Comment by Marius1311** [comment]
mh, that's a CellRank issue and has something to do with JAX and I think Apple silicon architectures - why do we get this here @michalk8?

**Comment by MarieCoutelier** [comment]
Hi,

I also tried installing everything on the computing cluster which is operated on CentOS 7. 
I ran 

```
conda install -c bioconda cellrank
pip install git+https://github.com/theislab/scvelo
```

The pip install gave me the following error message: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pygpcca 1.0.4 requires jinja2==3.0.3, but you have jinja2 3.1.2 which is incompatible.
```

but scvelo 0.3.0 got installed (conda list). 

In python, I could still not import scvelo: 

```
>>> import sys
>>> import scvelo as scv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/__init__.py", line 3, in <module>
    from scanpy import read, read_loom
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/__init__.py", line 17, in <module>
    from . import plotting as pl
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/_utils.py", line 36, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

I then tried correcting the jinja error with 
```
pip install jinja2==3.0.3
```
which correctly changed the version to 3.0.3, but did not solve the issue in python. 

So I'm unable to use scvelo in either my computer or the computing cluster, for now. 
If I can provide any additional info to identify the issue, please let me know :-)

Thanks a lot for your help!

Marie

**Comment by partrita** [comment]
> Hi,
> 
> I also tried installing everything on the computing cluster which is operated on CentOS 7. I ran
> 
> ```
> conda install -c bioconda cellrank
> pip install git+https://github.com/theislab/scvelo
> ```
> 
> The pip install gave me the following error message:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> pygpcca 1.0.4 requires jinja2==3.0.3, but you have jinja2 3.1.2 which is incompatible.
> ```
> 
> but scvelo 0.3.0 got installed (conda list).
> 
> In python, I could still not import scvelo:
> 
> ```
> >>> import sys
> >>> import scvelo as scv
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/__init__.py", line 3, in <module>
>     from scanpy import read, read_loom
>   File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/__init__.py", line 17, in <module>
>     from . import plotting as pl
>   File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
>     from ._anndata import (
>   File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
>     from . import _utils
>   File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank/lib/python3.11/site-packages/scanpy/plotting/_utils.py", line 36, in <module>
>     class _AxesSubplot(Axes, axes.SubplotBase, ABC):
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
> ```
> 
> I then tried correcting the jinja error with
> 
> ```
> pip install jinja2==3.0.3
> ```
> 
> which correctly changed the version to 3.0.3, but did not solve the issue in python.
> 
> So I'm unable to use scvelo in either my computer or the computing cluster, for now. If I can provide any additional info to identify the issue, please let me know :-)
> 
> Thanks a lot for your help!
> 
> Marie

Also, it happens to me. Therefore I just switched to python 3.8

**Pull request merged**
