### PR TITLE
Sym knn

### PR DESCRIPTION
**Pull request by michalk8**
Hey @VolkerBergen ,
@Marius1311 and I have some suggestions on how to modify one of the functions -
we've introduced a new version of `scv.tl.velocity_graph` - `scv.tl.velocity_graph_sym`, which forces the neighbors to be recomputed if someone tries to use a different number of neighbors (or if they were computed in a different basis) than previously computed.
There is still some more complicated behavior present (e.g. https://github.com/Marius1311/scvelo/pull/1#issuecomment-555298158), @Marius1311 will explain more.
Let us know what you think.

### CODE REVIEW

**Comment by Marius1311** [comment]
Thanks @michalk8 !  As Michal pointed out, we want to be quite careful in CellRank that the trancriptomic-similarity-based KNN graph (ts-graph) is *parallel* to the velocity-correlation based graph (vc-graph). In other words, we would like them to be computed always on exactly the same cells, so we can more easily combine both to get more robust transition probabilities.

In particular, when there is a pre-computed ts-KNN graph present with K neighbours, and a user calls `velocity_graph` with K-X neighbours, we don't want the original ts-KNN graph to be pruned so that each cell has precisely K-X neighbours, but we rather want to re-compute the ts-KNN graph and use that to build to vc-graph. The reason is that the pruned graph isn't symmetric any longer - hence the name of this branch :)

**Comment by VolkerBergen** [comment]
knn is generally not symmetric, only connectivities are. If you want to compute the transition matrix / velocity graph upon the connectivities, could you please adjust the PR accordingly. Should only be few edits in the VelocityGraph class and passing an additional attribute, e.g. `mode_neighbors`.

**Comment by Marius1311** [comment]
@michalk8 , could you open a separate PR in which we just introduce the `mode_neighbors` that Volker suggested above? That would mean
- computing the velocity graph on either distances or connectivities, depending on `mode_neighbors`
- if there is a precomputed KNN graph with K neighbors, but the user only want to use K-N neighbors, and `mode_neighbors` is connectivities, then we need to prune the graph back to the K-N nearest neighbors and recompute the connectivities, to get the symmetric indices. 
- leaving everything else as is, e.g. recursive neighbors etc.

**Comment by Marius1311** [comment]
> knn is generally not symmetric, only connectivities are.

In the standard definition, KNN graphs are symmetric, see e.g. Ulrike von Luxburg's tutorial on spectral clustering, page 2, https://arxiv.org/abs/0711.0189:

> k-nearest neighbor graphs: Here the goal is to connect vertex vi with vertex vj if vj is among the k nearest neighbors of vi. However, this definition leads to a directed graph, as the neighborhood relationship is not sym- metric. Now there are two ways of making this graph undirected. The first way is to simply ignore the directions of the edges, that is we connect vi and vj with an undirected edge if vi is among the k-nearest neighbors of vj or if vj is among the k-nearest neighbors of vi. The resulting graph is what is usually called the k-nearest neighbor graph. The second choice is to connect vertices vi and vj if both vi is among the k-nearest neighbors of vj and vj is among the k-nearest neighbors of vi. The resulting graph is called the mutual k-nearest neighbor graph. In both cases, after connecting the appropriate vertices we weight the edges by the similarity of the adjacent points.

The reason why I would like a symmetric graph here is because the theoretical foundations are given and I can build on that. 

>  If you want to compute the transition matrix / velocity graph upon the connectivities, could you please adjust the PR accordingly. Should only be few edits in the VelocityGraph class and passing an additional attribute, e.g. `mode_neighbors`.

**Comment by Marius1311** [comment]
@michalk8 , are you on this, or would you prefer me to do this? I would like to close this by tomorrow. @VolkerBergen , can you point us to where you think we should change the code?

**Comment by VolkerBergen** [comment]
It needs that additional parameter `mode_neighbors` and a module that recomputes connectivities, essentially this line https://github.com/theislab/scvelo/blob/b890ea30216f1f6e9a7366ed03bbcba715d002d7/scvelo/preprocessing/neighbors.py#L160 with pruned `knn_indices` and `knn_distances`.

**Comment by Marius1311** [comment]
@michalk8 , I will start doing this myself now.

**Comment by michalk8** [comment]
@Marius1311 Ok, I think it's the best, since I don't know how much time I'd have today. Thanks!

**Comment by Marius1311** [comment]
This PR can be closed - we solved the issue with #137. If we pre-compute a KNN graph and work with the parameters for `n_recurse_neighbors` and `mode_neighbors`, we can achieve what we originally were looking for.

**Comment by VolkerBergen** [comment]
see https://github.com/theislab/scvelo/pull/137

**Pull request closed without merging**
